"""
==========================================================================
AgriMind

Dynamic Executor

Module 6 + Module 5F

Workflow

Planner
      ↓
Specialist Agents
      ↓
Collaborative Reasoning
      ↓
Executive Decision Intelligence
      ↓
Recommendation Agent

Author : AgriMind Team
==========================================================================
"""

import time
import logging

from app.reasoning.collaborative_engine import collaborative_engine

from app.agents.weather_agent import weather_agent
from app.agents.soil_agent import soil_agent
from app.agents.satellite_agent import satellite_agent
from app.agents.market_agent import market_agent
from app.agents.historical_agent import historical_agent
from app.agents.recommendation_agent import recommendation_agent

from app.executive.executive_agent import executive_agent


logger = logging.getLogger(__name__)


class DynamicExecutor:

    """
    Executes the execution plan generated by the planner.
    """

    ####################################################################
    # Agent Registry
    ####################################################################

    def __init__(self):

        self.agent_registry = {

            "WeatherAgent": weather_agent,

            "SoilAgent": soil_agent,

            "SatelliteAgent": satellite_agent,

            "MarketAgent": market_agent,

            "HistoricalAgent": historical_agent

        }

    ####################################################################
    # Execute Specialists
    ####################################################################

    def execute_specialists(

        self,

        execution_plan,

        context

    ):

        outputs = {}

        for step in execution_plan:

            agent_name = step["agent"]

            ############################################################
            # Executive & Recommendation run later
            ############################################################

            if agent_name in (

                "ExecutiveAgent",

                "RecommendationAgent"

            ):

                continue

            ############################################################

            if agent_name not in self.agent_registry:

                logger.warning(

                    f"Unknown agent '{agent_name}'."

                )

                continue

            ############################################################

            logger.info(

                f"Running {agent_name}"

            )

            agent = self.agent_registry[agent_name]

            start = time.time()

            try:

                result = agent.execute(

                    context

                )

                result["agent"] = agent_name

                result["status"] = "completed"

                result["execution_time"] = round(

                    time.time() - start,

                    3

                )

            except Exception as e:

                logger.exception(e)

                result = {

                    "agent": agent_name,

                    "status": "failed",

                    "confidence": 0,

                    "error": str(e),

                    "execution_time": round(

                        time.time() - start,

                        3

                    )

                }

            outputs[agent_name] = result

        return outputs

    ####################################################################
    # Execute Pipeline
    ####################################################################

    def execute(

        self,

        plan,

        context

    ):

        ############################################################
        # Execute Specialist Agents
        ############################################################

        specialist_outputs = self.execute_specialists(

            plan["execution_plan"],

            context

        )

        ############################################################
        # Successful Outputs Only
        ############################################################

        successful_outputs = {

            name: result

            for name, result in specialist_outputs.items()

            if result.get("status") == "completed"

        }

        ############################################################
        # Collaborative Reasoning
        ############################################################

        reasoning = collaborative_engine.collaborative_reasoning(

            context,

            successful_outputs

        )

        ############################################################
        # Executive Decision Intelligence
        ############################################################

        try:

            executive = executive_agent.execute(

                context=context,

                reasoning=reasoning

            )

        except Exception as e:

            logger.exception(e)

            executive = {

                "status": "failed",

                "confidence": 0,

                "error": str(e)

            }

        ############################################################
        # Recommendation
        ############################################################

        try:

            recommendation = recommendation_agent.execute(

                context=context,

                reasoning=reasoning,

                executive=executive

            )

        except Exception as e:

            logger.exception(e)

            recommendation = {

                "agent": "RecommendationAgent",

                "status": "failed",

                "confidence": 0,

                "error": str(e)

            }

        ############################################################
        # Statistics
        ############################################################

        completed = len(successful_outputs)

        failed = len(specialist_outputs) - completed

        ############################################################

        return {

            "goal":

                plan["goal"],

            "execution_plan":

                plan["execution_plan"],

            ########################################################

            "specialists":

                specialist_outputs,

            ########################################################

            "reasoning":

                reasoning,

            ########################################################
            # Module 5F
            ########################################################

            "executive":

                executive,

            ########################################################

            "recommendation":

                recommendation,

            ########################################################

            "confidence":

                executive.get(

                    "confidence",

                    getattr(

                        reasoning,

                        "confidence",

                        0

                    )

                ),

            ########################################################

            "statistics": {

                "agents_planned":

                    len(plan["execution_plan"]),

                "agents_completed":

                    completed,

                "agents_failed":

                    failed,

                "planner_confidence":

                    plan.get(

                        "confidence",

                        0

                    ),

                "reasoning_confidence":

                    getattr(

                        reasoning,

                        "confidence",

                        0

                    ),

                "executive_confidence":

                    executive.get(

                        "confidence",

                        0

                    )

            }

        }


##########################################################################

executor = DynamicExecutor()