"""
==========================================================================
AgriMind

Crop Profile Builder

Uses Groq to generate a crop profile.

Pipeline

Groq
    ↓
JSON Parsing
    ↓
Validation
    ↓
Normalization
    ↓
Return Canonical Profile

Author : AgriMind Team
==========================================================================
"""

import json

from app.prompts.crop_profile_prompt import CROP_PROFILE_PROMPT
from app.utils.groq_client import groq_client
from app.knowledge.crop_profile_validator import crop_profile_validator


class CropProfileBuilder:

    """
    Builds canonical crop profiles using Groq.
    """

    ####################################################################
    # Build Prompt
    ####################################################################

    def build_prompt(self, crop):

        return f"""
{CROP_PROFILE_PROMPT}

======================================================================

Crop Name

{crop}

======================================================================

Generate the COMPLETE crop profile.

The JSON MUST strictly follow the schema.

Do not explain.

Return ONLY valid JSON.
"""

    ####################################################################
    # Parse JSON
    ####################################################################

    def parse(self, response):

        if response is None:
            raise ValueError("Groq returned no response.")

        response = response.strip()

        response = response.replace("```json", "")
        response = response.replace("```", "")
        response = response.strip()

        start = response.find("{")
        end = response.rfind("}")

        if start == -1 or end == -1:
            raise ValueError("Groq did not return valid JSON.")

        json_text = response[start:end + 1]

        try:
            return json.loads(json_text)

        except json.JSONDecodeError as e:

            raise ValueError(
                f"Invalid JSON generated by Groq:\n{e}"
            )

    ####################################################################
    # Build Profile
    ####################################################################

    def build(self, crop):

        print(f"Generating knowledge for '{crop}' using Groq...")

        prompt = self.build_prompt(crop)

        raw = groq_client.generate(

            prompt=prompt,

            system_prompt=(
                "You are an agricultural scientist. "
                "Return ONLY valid JSON."
            ),

            temperature=0.2

        )

        profile = self.parse(raw)

        ############################################################
        # Metadata
        ############################################################

        profile["generated_by"] = "Groq"

        ############################################################
        # Canonical Validation
        ############################################################

        profile = crop_profile_validator.validate(profile)

        print("✓ Crop profile validated.")

        return profile

    ####################################################################
    # Rebuild Existing Profile
    ####################################################################

    def rebuild(self, crop):

        print(f"Rebuilding crop profile for '{crop}'...")

        return self.build(crop)


##########################################################################

crop_profile_builder = CropProfileBuilder()