"""
==========================================================================
AgriMind

Canonical Crop Profile Prompt

This prompt defines the STANDARD crop profile used by every
AgriMind module.

Weather
Soil
Satellite
Market
Historical
Recommendation
Planner

All crop profiles generated by Groq MUST follow this schema.

Author : AgriMind Team
==========================================================================
"""

CROP_PROFILE_PROMPT = """
You are one of the world's leading agricultural scientists.

Generate a COMPLETE and SCIENTIFICALLY ACCURATE crop profile.

The profile will be used by an AI Decision Intelligence Platform.

Return ONLY VALID JSON.

Never explain.

Never use markdown.

Never omit fields.

==========================================================================
JSON SCHEMA
==========================================================================

{

    "crop":"",

    "scientific_name":"",

    "family":"",

    "type":"Annual | Perennial | Biennial",

    "category":"Cereal | Fruit | Vegetable | Pulse | Oilseed | Plantation | Spice | Fiber | Fodder | Other",

    "growth_duration_days":0,

    "growth_stages":[

        "Germination",

        "Vegetative",

        "Flowering",

        "Fruiting",

        "Harvest"

    ],

    "optimal_conditions":{

        "temperature":{

            "minimum":0,

            "maximum":0,

            "unit":"C"

        },

        "humidity":{

            "minimum":0,

            "maximum":0,

            "unit":"%"

        },

        "rainfall":{

            "minimum":0,

            "maximum":0,

            "unit":"mm/year"

        },

        "soil_ph":{

            "minimum":0,

            "maximum":0

        },

        "wind_speed":{

            "maximum":0,

            "unit":"km/h"

        },

        "sunlight_hours":{

            "minimum":0,

            "maximum":0

        }

    },

    "soil":{

        "preferred_texture":[

            "Clay",

            "Loam"

        ],

        "preferred_nitrogen":"Low | Medium | High",

        "preferred_organic_carbon":"Low | Medium | High",

        "preferred_drainage":"Poor | Moderate | Good"

    },

    "water":{

        "irrigation_type":"",

        "water_requirement":"Low | Medium | High",

        "critical_growth_stage":"",

        "recommended_frequency":""

    },

    "satellite_thresholds":{

        "ndvi":{

            "excellent":0.80,

            "healthy":0.65,

            "moderate":0.45,

            "poor":0.30

        },

        "ndwi":{

            "low_stress":0.30,

            "moderate_stress":0.10,

            "high_stress":0.00

        },

        "savi":{

            "low_exposure":0.60,

            "moderate_exposure":0.40,

            "high_exposure":0.20

        }

    },

    "market":{

        "keywords":[],

        "major_states":[],

        "major_countries":[],

        "harvest_season":"",

        "storage_capability":"Poor | Moderate | Good",

        "perishability":"Low | Medium | High"

    },

    "nutrition":{

        "primary_nutrients":[],

        "commercial_products":[]

    },

    "common_diseases":[

        {

            "name":"",

            "symptoms":"",

            "treatment":""

        }

    ],

    "common_pests":[

        {

            "name":"",

            "treatment":""

        }

    ],

    "fertilizer":{

        "recommended":"",

        "npk_ratio":"",

        "organic_options":[]

    },

    "yield":{

        "average_tonnes_per_hectare":0,

        "excellent_tonnes_per_hectare":0

    },

    "recommendations":{

        "irrigation":"",

        "fertilizer":"",

        "harvesting":"",

        "storage":""

    },

    "summary":"",

    "references":[

        "FAO",

        "ICAR"

    ]

}

==========================================================================
RULES
==========================================================================

1. Every field is mandatory.

2. Never return null.

3. Never omit a field.

4. Use scientifically accepted agricultural values.

5. Numeric values must be realistic.

6. NDVI, NDWI and SAVI thresholds must be crop-specific.

7. Market information must reflect the major producing regions.

8. Diseases and pests must be the most common ones.

9. Growth duration must be in days.

10. Rainfall should be annual rainfall.

11. Wind speed must represent the maximum safe cultivation wind speed.

12. Summary should be concise (less than 150 words).

13. References should include authoritative agricultural organizations.

Return ONLY VALID JSON.
"""